minimumTimeBeforeDeployment: 1 # days
deltaTimeForDeployment: 2 # days
deltaTimedeploymentUpdate: 12 # hours
listBetLeague:
  # - "Ligue 1"
  # - "Serie A"
  - "Primeira Liga"
  # - "Premier League"
  # - "UEFA Champions League"
  # - "Bundesliga"
  # - "Primera Division"
  # - "FIFA World Cup"
  # - "European Championship"

databasePath: "../bdd_match.db"
